export const personalityTypes = [
  {
    personality: "INTJ",
    title: "Architect",
    group: "Analysts",
    male: "/images/intj-architect-c-s2-v1-male.png",
    female: "/images/intj-architect-c-s2-v1-female.png",
  },
  {
    personality: "INTP",
    title: "Logician",
    group: "Analysts",
    male: "/images/intp-logician-s2-male.png",
    female: "/images/intp-logician-female.png",
  },
  {
    personality: "ENTJ",
    title: "Commander",
    group: "Analysts",
    male: "/images/entj-commander-s2-male.png",
    female: "/images/entj-commander-s2-female.png",
  },
  {
    personality: "ENTP",
    title: "Debater",
    group: "Analysts",
    male: "/images/entp-debater-s2-male.png",
    female: "/images/entp-debater-s2-female.png",
  },
  {
    personality: "INFJ",
    title: "Advocate",
    group: "Diplomats",
    male: "/images/infj-advocate-p-s2-v1-male.png",
    female: "/images/infj-advocate-p-s2-v1-female.png",
  },
  {
    personality: "INFP",
    title: "Mediator",
    group: "Diplomats",
    male: "/images/infp-mediator-s2-male.png",
    female: "/images/infp-mediator-c-s2-v1-female.png",
  },
  {
    personality: "ENFJ",
    title: "Protagonist",
    group: "Diplomats",
    male: "/images/enfj-protagonist-s2-male.png",
    female: "/images/enfj-protagonist-s2-female.png",
  },
  {
    personality: "ENFP",
    title: "Campaigner",
    group: "Diplomats",
    male: "/images/enfp-campaigner-s2-male.png",
    female: "/images/enfp-campaigner-s2-female.png",
  },
  {
    personality: "ISTJ",
    title: "Logistician",
    group: "Sentinels",
    male: "/images/istj-logistician-s2-male.png",
    female: "/images/istj-logistician-s2-female.png",
  },
  {
    personality: "ISFJ",
    title: "Defender",
    group: "Sentinels",
    male: "/images/isfj-defender-p-s2-v1-male.png",
    female: "/images/isfj-defender-p-s2-v1-female.png",
  },
  {
    personality: "ESTJ",
    title: "Executive",
    group: "Sentinels",
    male: "/images/estj-executive-s2-male.png",
    female: "/images/estj-executive-s2-female.png",
  },
  {
    personality: "ESFJ",
    title: "Consul",
    group: "Sentinels",
    male: "/images/esfj-consul-s2-male.png",
    female: "/images/esfj-consul-s2-female.png",
  },
  {
    personality: "ISTP",
    title: "Virtuoso",
    group: "Explorers",
    male: "/images/istp-virtuoso-s2-male.png",
    female: "/images/istp-virtuoso-s2-female.png",
  },
  {
    personality: "ISFP",
    title: "Adventurer",
    group: "Explorers",
    male: "/images/isfp-adventurer-s2-male.png",
    female: "/images/isfp-adventurer-s2-female.png",
  },
  {
    personality: "ESTP",
    title: "Entrepreneur",
    group: "Explorers",
    male: "/images/estp-entrepreneur-s2-male.png",
    female: "/images/estp-entrepreneur-s2-female.png",
  },
  {
    personality: "ESFP",
    title: "Entertainer",
    group: "Explorers",
    male: "/images/esfp-entertainer-s2-male.png",
    female: "/images/esfp-entertainer-s2-female.png",
  },
];
